name: pro_ftp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ftpconnect: ^3.0.0
  permission_handler: 12.0.1
  flutter_secure_storage: 9.2.2
  path_provider: ^2.1.6
  dartssh2: ^3.3.1
  google_mobile_ads: ^5.3.1
  flutter_local_notifications: ^17.0.0 # BİLDİRİM VE ARKA PLAN SERVİSİ İÇİN EKLENDİ

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^6.0.0

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
