name: Build Flutter App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Kopyala
      uses: actions/checkout@v3

    - name: Java 17 Kurulumu
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Flutter Kur
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Paketleri İndir
      run: flutter pub get

    - name: Generate App Icons
      run: flutter pub run flutter_launcher_icons

    - name: Keystore ve key.properties Dosyalarını GitHub Secrets'tan Oluştur
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      run: |
        # Base64 metnini tekrar dosyaya çeviriyoruz
        echo "$KEYSTORE_BASE64" | base64 --decode --ignore-garbage > android/app/upload_keystore.jks
        
        # key.properties dosyasını sunucuda anlık olarak yaratıyoruz
        echo "storePassword=$STORE_PASSWORD" > android/app/key.properties
        echo "keyPassword=$KEY_PASSWORD" >> android/app/key.properties
        echo "keyAlias=$KEY_ALIAS" >> android/app/key.properties
        echo "storeFile=upload_keystore.jks" >> android/app/key.properties

    - name: Eksik Android Platformlarını Kur
      run: yes | sdkmanager "platforms;android-37" "platforms;android-36" "platforms;android-35"

    - name: Release AAB Derle
      run: flutter build appbundle --release --android-skip-build-dependency-validation
      
    - name: AAB'yi Yükle
      uses: actions/upload-artifact@v4
      with:
        name: FTP-PRO-AAB-RELEASE
        path: build/app/outputs/bundle/release/app-release.aab

    - name: Release APK Derle
      run: flutter build apk --release --android-skip-build-dependency-validation
      
    - name: APK'yi Yükle
      uses: actions/upload-artifact@v4
      with:
        name: FTP-PRO-APK-RELEASE
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Debug APK Derle
      run: flutter build apk --debug

    - name: Debug APK'yi Yükle
      uses: actions/upload-artifact@v4
      with:
        name: FTP-PRO-APK-DEBUG
        path: build/app/outputs/flutter-apk/app-debug.apk
